manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    
    # ↓ この3行を完全に削除してください！
    - name: cirque-input-module
      remote: petejohanson
      revision: main
      
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
  self:
    path: config
