manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
      
    # ↓ここを変更！ zmk-pmw3610-driver を消して、Cirqueのモジュールに書き換えます
    - name: cirque-input-module
      remote: petejohanson
      revision: main
      
    # ↓RGBLEDウィジェットはそのまま残します
    - name: zmk-rgbled-widget
      remote: petejohanson
      revision: main
  self:
    path: config
