# Bluetoothの名前
CONFIG_ZMK_KEYBOARD_NAME="ZaruBallTP"

# Pointing & Input
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_INPUT=y
CONFIG_INPUT_PINNACLE=y

# I2C
CONFIG_I2C=y

# XIAO BLE NFCピンの開放
CONFIG_NFCT_PINS_AS_GPIOS=y

# 省電力設定
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# バッテリー報告
CONFIG_ZMK_BATTERY_REPORTING=y

# LEDウィジェット
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_INTERVAL_MS=500
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
